my = {'name', [3,4]}
print(my) # will cause error